server:
  port: 2501

spring:
  application:
    name: spring-boot-postgres-data-source
  datasource:
    url: jdbc:postgresql://10.0.0.137:5432/postgres_data_source
    driver-class-name: org.postgresql.Driver
    username: postgres_data_source
    password: postgres_data_source
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool-POSTGRES-DATA-SOURCE
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
      show-sql: false